### ISSUE TITLE
Array of Files

### ISSUE THREAD

**Issue by jasonlor** [ferristseng/rust-multipart-rfc7578#11]
Any examples on how uploading an array of files/directory would work?

**Comment by sameer** [comment]
See [rust-ipfs-api add_path](https://github.com/ferristseng/rust-ipfs-api/blob/0cf5be505470b2bcaf837d93239283be1f9a4a1e/ipfs-api/src/client.rs#L424)

**Comment by jasonlor** [comment]
Thanks!
