### ISSUE TITLE
Update dependencies to support async.await

### ISSUE THREAD

**Issue by gliderkite** [ferristseng/rust-multipart-rfc7578#16]
Update dependencies such as `futures` to `0.3` to support the new `async.await` feature for `hyper 0.13` and `actix 2.0`.

**Comment by Dowwie** [comment]
This is a much more demanding port due to breaking changes when the dependencies are upgraded.  

@ferristseng were you planning on upgrading soon?

**Comment by ferristseng** [comment]
Going to release 2 new version for now, `0.4-rc` for hyper, and `0.3-rc` for actix. If these both work with `rust-ipfs-api`, I'll promote to `0.4` and `0.3`

**Comment by Dowwie** [comment]
@ferristseng thanks for updating!  Note that Nikolay will very likely be releasing the actix projects by end of this year.  You may want to consider waiting to publish a new multipart crate until final dependencies are available.   I can't comment on `rust-ipfs-api` support. :)

**Comment by Dowwie** [comment]
@ferristseng thanks very much for upgrading.  actix-web 2.0 will likely be released before end of this year, so plan on publishing this crate accordingly :)
