### ISSUE TITLE
upgrade to hyper v1

### ISSUE THREAD

**Issue by iohzrd** [ferristseng/rust-multipart-rfc7578#34]
I'm trying to upgrade my folk to hyper v1 (and therefore http to v1), so I can upgrade rust-ipfs-api as well. I think I have it mostly done, but i'm having trouble in `hyper/src/body.rs`.

hyper v1 renamed the `Body` struct to `Incoming`, so I've changed all the instances of `Body` accordingly, but I can't seem to implement `impl Into<hyper::body::Incoming> for Body` properly.

Wondering if I can get some help.

**Comment by lsunsi** [comment]
I'm also interested in this! This lib is the last one in my long line of upgrade to 1.0.

**Comment by jothan** [comment]
PR #35 should fix most of these issues. @iohzrd, @lsunsi,  please test if possible.
